#DATABASE
POSTGRESQL_USERNAME: sirocu
POSTGRESQL_PASSWORD: sirocu
POSTGRESQL_HOST: 127.0.0.1
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: sipoint

#SERVER
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085

#JWT
JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}
